name: Auto Commit
on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 3223A | KACHIGGA
        uses: actions/checkout@v2

      - name: Auto-commit changes
        run: |
          git add -A
          git commit -m "Auto-commit: $(date)"
          git push
